# This file was *autogenerated* from the file diffie.sage
from sage.all_cmdline import *   # import sage library
_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_10 = Integer(10); _sage_const_191 = Integer(191); _sage_const_133 = Integer(133)
# the diffie hellman algorithm.
# Both public
p =random_prime(_sage_const_2 ,(_sage_const_2 **_sage_const_10 )-_sage_const_1 ) # prime number
p = _sage_const_191 
print ":",p
s = primitive_root(p)
print 'S',s
r = mod(s,p) # primative root
print 'r',r
#private values for alice and bob
alice_rand = randint(_sage_const_1 ,p)
alice_rand = _sage_const_133 
print "alice:",alice_rand
bob_rand = randint(_sage_const_1 ,p)

#numbers that we transfer, public
a = r ** alice_rand % p
b = r ** bob_rand % p

print a, b
# gets the same value for bob and alice as the key
print a ** bob_rand % p
print b ** alice_rand % p
