# This file was *autogenerated* from the file diffie.sage
from sage.all_cmdline import *   # import sage library
_sage_const_30 = Integer(30); _sage_const_20 = Integer(20); _sage_const_10 = Integer(10); _sage_const_1 = Integer(1)
# the diffie hellman algorithm.
# Both public
p =random_prime(_sage_const_10 **_sage_const_20 ,_sage_const_10 **_sage_const_30 ) # prime number
r = mod(primitive_root(p),p) # primative root

#private values for alice and bob
alice_rand = randint(_sage_const_1 ,p)
bob_rand = randint(_sage_const_1 ,p)

#numbers that we transfer, public
a = r ** alice_rand
b = r ** bob_rand

print a, b
# gets the same value for bob and alice as the key
print a ** bob_rand
print b ** alice_rand
